In [128]:
from datetime import datetime
startTime = datetime.now()

filepath = 'test.txt'

import numpy

def run_program(data):
    grid = numpy.zeros((17, 1000))
    #print(grid)
    pos = (0, 500)
    grid[pos] = 2
    for data_point in data:
        #print(data_point)
        first = data_point[0].split('=')
        second = data_point[1].split('=')[1].split('..')
        a, b, c, d = [first[0]] + [int(i) for i in [first[1], second[0], second[1]]]
        
        for i in range(c, d + 1):
            if a == 'x':
                grid[i][b] = 1
            elif a == 'y':
                grid[b][i] = 1
            else:
                pass
            
    min_x, max_x, max_y = pos[1]-2, pos[1] + 2, 1
    print(range(min_x, max_x))
    for i in range(35):
        print(i)

        for y in range(0, max_y):
            for x in range(min_x, max_x):
                #print(y, x)
                if grid[y][x] == 2:
                    if grid[y+1][x] == 0:
                        grid[y+1][x] = 2
                        if y+1 == max_y:
                            max_y += 1
                    elif grid[y+1][x] == 1:
                        if grid[y][x-1] == 0:
                            grid[y][x-1] = 2
                            if x == min_x:
                                min_x -= 1
                        if grid[y][x+1] == 0:
                            grid[y][x+1] = 2
                            if x + 1 == max_x:
                                max_x += 1
                                
                elif grid[y][x] == 0 and grid[y+1][x] == 2:
                    valid_up_water, valid_up_wall = False, False
                    for a in range(x, 1000):
                        if grid[y+1][a] == 0:
                            break
                        if grid[y][a] == 2:
                            valid_up_water = True
                            #print('WATER RIGHT')
                            break
                        elif grid[y][a] == 1:
                            valid_up_wall = True
                            #print('WALL RIGHT')
                            break
                    for a in range(x-1, 0, -1):
                        #print(grid[y][a])
                        if grid[y+1][a] == 0:
                            break
                        if grid[y][a] == 2 and valid_up_wall:
                            #print('WATER LEFT')
                            valid_up_water = True
                            break
                        elif grid[y][a] == 1 and valid_up_water:
                            #print('WALL LEFT')
                            valid_up_wall = True
                            break
                    if valid_up_water and valid_up_wall:# and grid[y+1][x-1] != 0 and grid[y+1][x+1] != 0:
                        grid[y][x] = 2
                elif grid[y][x] == 0 and grid[y+1][x] == 1:
                    if y == 2 and x == 501 and i == 10:
                        print('start')
                    valid_side_water, atleast_one_water = False, False
                    for a in range(x, 1000):
                        if grid[y][a] == 0:
                            break
                        elif grid[y][a] == 1 and atleast_one_water:
                            valid_side_water = True
                        elif grid[y][a] == 2:
                            atleast_one_water = True

                    atleast_one_water = False
                    for a in range(x-1, 0, -1):
                        if y == 2 and x == 501 and i == 10:
                            print(y, a)
                            print(grid[y][a])
                            print(valid_side_water, atleast_one_water)
                        if grid[y][a] == 0:
                            break
                        elif grid[y][a] == 1 and atleast_one_water:
                            valid_side_water = True
                        elif grid[y][a] == 2:
                            atleast_one_water = True

                            
                    if valid_side_water:
                        grid[y][x] = 2
                        
                        
                        
        for y in grid[0:15]:
            print(y[493:508])
            
        print()
    return 1
        
data = []
with open(filepath, 'r') as f:
    for line in f.readlines():
        data.append(line.strip().split(','))
f.close()

print(run_program(data[:]))
#print(run_program(data[:]))
print(str(datetime.now() - startTime)[:-3])

range(498, 502)
0
[0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

1
[0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0. 1. 0. 2. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.

In [68]:
print(list(range(7, 4)))

[]
